### ISSUE TITLE
OpenWRT/LEDE pppoe problem

### ISSUE THREAD

**Issue by terba** [kravietz/blacklist-scripts#6]
First of all, thanks for this script!
On LEDE using pppoe wan the `wan_iface=$(uci get network.wan.ifname)` line sets `eth0.2` not `pppoe-wan` so blocking was not working. I replaced the line with `IN_OPT=""` and it works now.

**Comment by pbarwich** [comment]
Or you can replace line "wan_iface=$(uci get network.wan.ifname)", with "wan_iface=pppoe-wan". Line 71 (including blanks).

**Comment by kravietz** [comment]
@pbarwich @terba  but what if wan ifname is something else? I don't have any LEDE instance to test on, so what is the proper way of determining the wan interface there?

**Comment by nulano** [comment]
My system does not have `pppoe-wan`, I had to edit the script to use `eth0.2`. The correct edit would have been `$(uci get network.pppoe.ifname)` since that is probably the name of @terba's network. The best solution would probably be a config parameter at the top of the script to use `$(uci get network.${WAN_NETWORK}.ifname)`, and to mention this in the readme.
